
title: Johnny's Blog
email: sharsheev01@gmail.com
author: Jsharsh33v

markdown: kramdown
kmarkdown:
  input: GFM

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-spaceship
